descope/descope-kotlin

.editorconfig, .github/pull_request_template.md, .github/workflows/ci.yml, .github/workflows/publish.yml, README.md, build.gradle, descopesdk/build.gradle, renovate.json
Adding a publish workflow to release to maven central
There's room to make this more generic by taking information from the environment, 1000 bonusly to the person who adds it
=> feat: publishing workflow

.github/workflows/detekt.yml
=> feat(ci): add code scanning

README.md, descopesdk/src/main/java/com/descope/internal/routes/Flow.kt
https://github.com/descope/etc/issues/310
Add flow documentation to README.
=> Add flow documentation to README

descopesdk/src/main/java/com/descope/Descope.kt, descopesdk/src/main/java/com/descope/internal/http/DescopeClient.kt
Fixes https://github.com/descope/etc/issues/3091
DeliveryMethod lowercased when used in routes
=> Fix delivery method casing

README.md, build.gradle, descopesdk/src/main/java/com/descope/internal/http/DescopeClient.kt, descopesdk/src/main/java/com/descope/internal/routes/Password.kt, descopesdk/src/main/java/com/descope/sdk/Routes.kt
related to https://github.com/descope/etc/issues/3800
Change `Descope.password.replace(...)` return value with authentication info
=> Replace password - return a session

README.md, descopesdk/src/main/java/com/descope/Descope.kt, descopesdk/src/main/java/com/descope/session/Lifecycle.kt, descopesdk/src/main/java/com/descope/session/Manager.kt, descopesdk/src/main/java/com/descope/session/Session.kt, descopesdk/src/main/java/com/descope/session/Storage.kt, descopesdk/src/main/java/com/descope/types/User.kt
Fix documentation across the repo.
=> Fixed documentation

build.gradle, descopesdk/build.gradle, descopesdk/src/main/java/com/descope/internal/http/Responses.kt, descopesdk/src/main/java/com/descope/internal/others/Utils.kt, descopesdk/src/main/java/com/descope/internal/routes/Shared.kt, descopesdk/src/main/java/com/descope/session/Storage.kt, descopesdk/src/main/java/com/descope/types/User.kt, descopesdk/src/test/java/com/descope/session/JsonTest.kt
https://github.com/descope/etc/issues/4615
Add `customAttributes` property to the `DescopeUser` object
-   [X] Tests
-   [X] Documentation (if applicable)
=> Add custom attributes to the user object

README.md, descopesdk/src/main/java/com/descope/sdk/Sdk.kt
=> Bump version

descopesdk/src/main/java/com/descope/internal/http/DescopeClient.kt, descopesdk/src/main/java/com/descope/internal/http/HttpClient.kt, descopesdk/src/main/java/com/descope/internal/http/Responses.kt, descopesdk/src/main/java/com/descope/internal/routes/Shared.kt, descopesdk/src/main/java/com/descope/session/Storage.kt, descopesdk/src/main/java/com/descope/types/Others.kt, descopesdk/src/main/java/com/descope/types/User.kt
https://github.com/descope/etc/issues/4931
Support given, middle and family names for users
-   [x] Tests
=> Support given, middle and family names

build.gradle, descopesdk/src/main/java/com/descope/internal/http/DescopeClient.kt, descopesdk/src/main/java/com/descope/internal/routes/EnchantedLink.kt, descopesdk/src/main/java/com/descope/internal/routes/MagicLink.kt, descopesdk/src/main/java/com/descope/internal/routes/Otp.kt, descopesdk/src/main/java/com/descope/sdk/Routes.kt, descopesdk/src/main/java/com/descope/types/Others.kt
https://github.com/descope/etc/issues/3941
Support `UpdateOptions` for update functions
-   [X] Tests
-   [X] Documentation (if applicable)
=> Add UpdateOptions

README.md, descopesdk/src/main/java/com/descope/internal/routes/Flow.kt, descopesdk/src/main/java/com/descope/sdk/Routes.kt
Fixes https://github.com/descope/etc/issues/5062
Add custom scheme for opera users
-   [X] Tests
-   [X] Documentation (if applicable)
=> Add custom scheme for opera users

descopesdk/src/main/java/com/descope/internal/http/DescopeClient.kt, descopesdk/src/main/java/com/descope/sdk/Config.kt, descopesdk/src/test/java/com/descope/internal/http/DescopeClientTest.kt, descopesdk/src/test/java/com/descope/internal/others/JsonTest.kt, descopesdk/src/test/java/com/descope/types/DescopeExceptionTest.kt
https://github.com/descope/etc/issues/5226#event-11411420436
- Extract region from project ID
- Move tests to their proper package
-   [x] Tests
=> Extract region from project ID

README.md, descopesdk/src/main/java/com/descope/sdk/Sdk.kt
=> Bump version to 0.9.9

README.md, descopesdk/src/main/java/com/descope/sdk/Sdk.kt
=> Bump version to 0.10.0

README.md, build.gradle, descopesdk/src/main/java/com/descope/sdk/Sdk.kt
=> Revert Kotlin v2

README.md, descopesdk/src/main/java/com/descope/android/DescopeFlowCoordinator.kt, descopesdk/src/main/java/com/descope/android/DescopeFlowView.kt, descopesdk/src/main/java/com/descope/sdk/Sdk.kt
https://github.com/descope/etc/issues/5992
Use last instead of second
-   [x] Tests
=> Native flow adjustments

README.md, descopesdk/src/main/java/com/descope/android/DescopeFlowCoordinator.kt, descopesdk/src/main/java/com/descope/android/DescopeFlowView.kt
https://github.com/descope/etc/issues/5992
Change flow lifecycle to listener and move to view
-   [x] Tests
=> Change flow lifecycle to listener and move to view

descopesdk/src/main/java/com/descope/internal/http/DescopeClient.kt, descopesdk/src/main/java/com/descope/internal/http/Responses.kt, descopesdk/src/main/java/com/descope/internal/others/Utils.kt, descopesdk/src/main/java/com/descope/internal/routes/Auth.kt, descopesdk/src/main/java/com/descope/sdk/Routes.kt, descopesdk/src/main/java/com/descope/types/Tenant.kt, descopesdk/src/test/java/com/descope/internal/routes/AuthTest.kt, descopesdk/src/test/java/com/descope/internal/routes/TestUtils.kt
https://github.com/descope/etc/issues/7070
Add `MeTenants` API to support retrieving the tenants for a user
-   [x] Tests
=> Add get tenants API

README.md, descopesdk/src/main/java/com/descope/android/DescopeFlowCoordinator.kt, descopesdk/src/main/java/com/descope/sdk/Sdk.kt
Add protection against flow `ready` race-condition
=> Add protection against ready race-condition

descopesdk/src/main/java/com/descope/android/DescopeFlowCoordinator.kt, descopesdk/src/main/java/com/descope/android/DescopeFlowHook.kt, descopesdk/src/main/java/com/descope/android/DescopeFlowView.kt, descopesdk/src/main/java/com/descope/internal/others/ActivityHelper.kt
Fixes https://github.com/descope/etc/issues/8779
- Add flow hooks
- Expose flow state to the flow view
-  [x] Tests
-  [x] Documentation (if applicable)
=> Flow hooks

descopesdk/src/main/java/com/descope/android/DescopeFlowCoordinator.kt, descopesdk/src/main/java/com/descope/internal/http/ClientErrors.kt
https://github.com/descope/etc/issues/9527
https://github.com/descope/descope-kotlin/pull/179
- Add handling for HTTP errors
- Improve network error messages
=> Add handling for HTTP errors and improve network error messages

build.gradle, descopesdk/build.gradle
Update dependencies and android versions:
- Android library plugin version
- compile and target SDKs to 35
- AndroidX Lifecycle
- AndroidX credentials
=> Update dependencies and android versions

README.md, descopesdk/src/main/java/com/descope/types/Error.kt
https://github.com/descope/etc/issues/9530#issuecomment-2686281030
Document error handling in more detail
=> Document error handling in more detail

descopesdk/src/main/java/com/descope/session/Lifecycle.kt
https://github.com/descope/descope-kotlin/pull/178
- Fix incorrect lifecycle variable use.
=> Fix incorrect lifecycle variable use

README.md, descopesdk/src/main/java/com/descope/android/DescopeFlowCoordinator.kt, descopesdk/src/main/java/com/descope/internal/routes/Passkey.kt, descopesdk/src/main/java/com/descope/sdk/Sdk.kt
Fixes https://github.com/descope/etc/issues/9695
- Enforce single bridge operation at a time
- Stop treating bridge cancelations as errors
- (unrelated) add additional explicit webauthn error 
-   [x] Tests
=> Single execution enforecment

README.md, descopesdk/src/main/java/com/descope/android/DescopeFlowCoordinator.kt, descopesdk/src/main/java/com/descope/internal/others/ActivityHelper.kt, descopesdk/src/main/java/com/descope/sdk/Config.kt, descopesdk/src/main/java/com/descope/sdk/Sdk.kt
https://github.com/descope/etc/issues/9695
- Fix custom tab launch logic
- Fix duplicate flow view initializations
- Add debug logging enforcement
-   [x] Tests
=> Fix custom tab launch and flow view initialization

descopesdk/src/main/java/com/descope/android/DescopeFlowCoordinator.kt
Pass JWT response parsing error via callback
-   [x] Tests
=> Pass JWT response parsing error via callback

README.md, descopesdk/src/main/java/com/descope/Descope.kt, descopesdk/src/main/java/com/descope/android/DescopeFlowCoordinator.kt, descopesdk/src/main/java/com/descope/android/DescopeFlowView.kt, descopesdk/src/main/java/com/descope/sdk/Sdk.kt, descopesdk/src/test/java/com/descope/session/TokenTest.kt
https://github.com/descope/etc/issues/8190
- Change coordinator to not expect an initialized SDK for react native
- Bump version to 0.13.3
-   [x] Tests
=> React native changes

descopesdk/src/main/java/com/descope/internal/http/DescopeClient.kt, descopesdk/src/main/java/com/descope/internal/http/SystemInfo.kt, descopesdk/src/main/java/com/descope/sdk/Sdk.kt, descopesdk/src/test/java/com/descope/internal/routes/EnchantedLinkTest.kt, descopesdk/src/test/java/com/descope/internal/routes/MagicLinkTest.kt, descopesdk/src/test/java/com/descope/internal/routes/PasswordTest.kt, descopesdk/src/test/java/com/descope/internal/routes/TestUtils.kt
https://github.com/descope/etc/issues/9778
Add more default headers
-   [x] Tests
=> Add more default headers

README.md, descopesdk/src/main/java/com/descope/internal/http/SystemInfo.kt, descopesdk/src/main/java/com/descope/sdk/Sdk.kt, descopesdk/src/main/java/com/descope/session/Lifecycle.kt, descopesdk/src/main/java/com/descope/session/Manager.kt
https://github.com/descope/etc/issues/9870
Add `DescopeSessionManager.Listener` to allow the caller to get notified when the session changes when it is set, refreshed or cleared.
-   [x] Tests
=> Add `DescopeSessionManager.Listener`

descopesdk/src/main/java/com/descope/android/DescopeFlowCoordinator.kt
Move flow state update into the main thread
-   [x] Tests
=> Move flow state update into the main thread

descopesdk/src/main/java/com/descope/internal/http/DescopeClient.kt
https://github.com/descope/etc/issues/10013
Add descope project ID header
=> Add descope project ID header

build.gradle
https://central.sonatype.org/faq/what-is-different-between-central-portal-and-legacy-ossrh/
https://github.com/descope/etc/issues/10678
=> chore: migrate to central

descopesdk/build.gradle.kts, descopesdk/src/main/java/com/descope/Descope.kt, descopesdk/src/main/java/com/descope/android/DescopeFlow.kt, descopesdk/src/main/java/com/descope/android/DescopeFlowCoordinator.kt, descopesdk/src/main/java/com/descope/android/DescopeFlowHook.kt, descopesdk/src/main/java/com/descope/android/DescopeFlowView.kt, descopesdk/src/main/java/com/descope/android/Utils.kt, descopesdk/src/main/java/com/descope/extensions/URLConnection.kt, descopesdk/src/main/java/com/descope/internal/http/HttpClient.kt, descopesdk/src/main/java/com/descope/internal/http/SystemInfo.kt, descopesdk/src/main/java/com/descope/internal/others/Utils.kt, descopesdk/src/main/java/com/descope/internal/routes/EnchantedLink.kt, descopesdk/src/main/java/com/descope/internal/routes/Flow.kt, descopesdk/src/main/java/com/descope/internal/routes/OAuth.kt, descopesdk/src/main/java/com/descope/internal/routes/Passkey.kt, descopesdk/src/main/java/com/descope/internal/routes/Shared.kt, descopesdk/src/main/java/com/descope/session/Manager.kt, descopesdk/src/main/java/com/descope/session/Session.kt, descopesdk/src/main/java/com/descope/session/Storage.kt, descopesdk/src/main/java/com/descope/session/Token.kt, descopesdk/src/main/java/com/descope/types/Error.kt, descopesdk/src/main/java/com/descope/types/Others.kt, descopesdk/src/test/java/com/descope/internal/routes/PasswordTest.kt, descopesdk/src/test/java/com/descope/internal/routes/TestUtils.kt, gradle/libs.versions.toml, gradle/wrapper/gradle-wrapper.properties, settings.gradle.kts
- Kotlin major version upgrade to 2.2.0
- Android Gradle Plugin updated to version 8.11.1 and Gradle to 8.14.3
- All dependencies on latest version
- Minor lint fixes throughout
-   [x] Tests
=> Update kotlin and deps
